# Ubuntu 14.04.x + Oracle JRE 8
FROM cleawing/elasticsearch:base

MAINTAINER pjpires@gmail.com

# Override elasticsearch.yml config
ADD elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
